version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 14
  open-pull-requests-limit: 10
  groups:
    github:
      patterns:
      - actions/*
      - github/*
    jdx:
      patterns:
      - jdx/*
    other:
      patterns:
      - '*'
  reviewers:
  - mkobit
  assignees:
  - mkobit
  commit-message:
    prefix: chore(deps)
    include: scope
- package-ecosystem: uv
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 14
  open-pull-requests-limit: 10
  groups:
    astral:
      patterns:
      - ruff
      - uv
      - ty
    pytest:
      patterns:
      - pytest
      - pytest-*
    trusted-libs:
      patterns:
      - pydantic
      - pydantic-*
    whenever:
      patterns:
      - whenever
    python-dependencies:
      patterns:
      - '*'
  reviewers:
  - mkobit
  assignees:
  - mkobit
  commit-message:
    prefix: chore(deps)
    include: scope
