-- Hello World Hammerspoon Configuration
-- Generated by Bazel

-- Display a notification when Hammerspoon loads
hs.notify.new({title="Hammerspoon", informativeText="Hello World from Hammerspoon!"}):send()

-- Print to console
print("Hello World from Hammerspoon configuration!")

-- Simple hotkey to show alert
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "H", function()
  hs.alert.show("Hello World!")
end)