"""
Tmux configuration rules and macros.
"""

def tmux_config(
    name,
    srcs,
    sections = None,
    file_name = "tmux.conf",
    visibility = None,
):
    """Generate a tmux configuration file.

    Args:
        name: Target name.
        srcs: Source config files to include.
        sections: Optional ordered sections to include.
        file_name: Output filename.
        visibility: Target visibility.
    """
    if sections:
        _sections = sections
    else:
        _sections = []

    native.genrule(
        name = name,
        srcs = srcs,
        outs = [file_name],
        cmd = """
        echo "# THIS FILE IS GENERATED BY BAZEL - DO NOT EDIT DIRECTLY" > $@
        echo "# Generated tmux configuration" >> $@
        echo "# Generated at $$(date)" >> $@
        echo "" >> $@
        
        # Include all source files
        for src in $(SRCS); do
            echo "# Including $$(basename $$src)" >> $@
            cat $$src >> $@
            echo "" >> $@
        done

        echo "# End of generated configuration" >> $@
        """,
        visibility = visibility,
    )
    
    # Return the file path for integration with other rules
    native.filegroup(
        name = name + "_fg",
        srcs = [":" + name],
        visibility = visibility,
    )

def tmux_config_sections(name, visibility = None, **kwargs):
    """Create a tmux configuration with ordered sections.
    
    Each section should be provided as a named argument with a file.
    
    Example:
      tmux_config_sections(
          name = "my_tmux_conf",
          header = "//path/to:header.tmux",
          status = "//path/to:status.tmux",
      )
    """
    # Collect all sections
    sections = []
    section_targets = []
    
    # Generate a sorted list based on order provided
    for section_name, section_file in sorted(kwargs.items()):
        sections.append(section_name)
        section_targets.append(section_file)
    
    # Generate the configuration
    native.genrule(
        name = name,
        srcs = section_targets,
        outs = [name + ".conf"],
        cmd = """
        echo "# THIS FILE IS GENERATED BY BAZEL - DO NOT EDIT DIRECTLY" > $@
        echo "# Generated tmux configuration with sections: {}" >> $@
        echo "# Generated at $$(date)" >> $@
        echo "" >> $@
        
        # Include all sections
        for section in $(SRCS); do
            echo "# Including $$(basename $$section)" >> $@
            cat $$section >> $@
            echo "" >> $@
        done

        echo "# End of generated configuration" >> $@
        """.format(" ".join(sections)),
        visibility = visibility,
    )