-- Base Hammerspoon configuration
-- Generated by Bazel

-- Print a message to the console when Hammerspoon loads this config
hs.console.printStyledtext("Hammerspoon config loaded")

-- Basic window management
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "left", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()
  
  f.x = max.x
  f.y = max.y
  f.w = max.w / 2
  f.h = max.h
  win:setFrame(f)
end)

-- Load the Rectangle Pro API
local RectanglePro = require("rectangle-pro")

-- Example hotkey using the Rectangle Pro API
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "y", function()
  local ok, err = RectanglePro.leftHalf()
  if not ok then
    hs.console.printStyledtext("Rectangle Pro action failed: " .. err)
  end
end)

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "right", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()
  local screen = win:screen()
  local max = screen:frame()
  
  f.x = max.x + (max.w / 2)
  f.y = max.y
  f.w = max.w / 2
  f.h = max.h
  win:setFrame(f)
end)