# ASDF Version Manager configuration
# Used by run_once_install-asdf.sh.tmpl to configure asdf plugins
# Binary is installed via .chezmoiexternals to ~/.local/bin/asdf
#
# Plugin shortnames reference:
# - When git_url is omitted, asdf uses the official shortname registry
# - See: https://github.com/asdf-vm/asdf-plugins
#
# References:
# - https://asdf-vm.com/guide/getting-started.html
# - https://github.com/asdf-vm/asdf/releases

[asdf]
  enabled = true
  version = "0.18.0"

  # Language version management plugins
  # Plugins are installed/removed based on this array
  plugins = [
    { name = "nodejs" },     # https://github.com/asdf-vm/asdf-nodejs
    { name = "python" },     # https://github.com/danhper/asdf-python
    { name = "java" },       # https://github.com/halcyon/asdf-java
    { name = "golang" },     # https://github.com/asdf-community/asdf-golang
    { name = "rust" },       # https://github.com/code-lever/asdf-rust
  ]

[asdf.checksums]
darwin_arm64 = "5c82af09a9b17bb71195cd1c0a6baa1c7c4491b837ac601c42853e553b50a618"
darwin_amd64 = "aa698a8146fcdcb1145224ffb135f1b3ce2b7e4c2daceb00229ff82bb923d13b"
linux_amd64 = "4d3007070166cb0a652af26c3f0462b021e04cb26c4ab13894d13689da89f5b8"
linux_arm64 = "1749b89039e4af51b549aa0919812fd68722c1a26a90eaf84db0b46a39f557a9"