[eza]
version = "0.23.3"

[eza.installation]
# macOS: use package-manager (Homebrew), eza doesn't publish macOS binaries to GitHub releases
darwin = "package-manager"
# Linux: use external-sources for pre-built binaries from GitHub releases
linux = "external-sources"

[eza.checksums]
linux_amd64 = "9394077c94ced5a39b895092a4e59b21c3949b414a1affb08c47be6a3af17eca"
linux_arm64 = "333246365f1a3325df1068ff8bc994ea3a3e04abe4e118fa11015d589c5cc41d"