[eza]
version = "0.23.4"

[eza.installation]
# macOS: use package-manager (Homebrew), eza doesn't publish macOS binaries to GitHub releases
darwin = "package-manager"
# Linux: use external-sources for pre-built binaries from GitHub releases
linux = "external-sources"

[eza.checksums]
linux_amd64 = "d231bb3ee33b08c76279b5888845dceb7034d055c42bb9be46dbe0dae39394df"
linux_arm64 = "366e8430225f9955c3dc659b452150c169894833ccfef455e01765e265a3edda"