"""
Implementation of Git configuration rules.
"""

load("//rules/common:rule_utils.bzl", "create_config_rule", "create_config_test_rule")

# Create git_config rule using common utilities
git_config = create_config_rule(
    rule_name = "git",
    file_extension = ".gitconfig",
    mnemonic = "GitConfig",
    allowed_extensions = None,  # Allow all file types
    header_template = "# Git configuration generated by Bazel",
    footer_template = "# End of generated Git configuration",
)

# Define validation commands for git
_GIT_VALIDATION_COMMANDS = [
    # Validate syntax by parsing the config
    '"{tool_path}" config --file "{config_path}" --list || {{ echo "Git configuration has syntax errors"; exit 1; }}'
]

# Create git_test rule using common utilities
git_test = create_config_test_rule(
    rule_name = "git",
    toolchain_type = "//toolchains/git:toolchain_type",
    validation_commands = _GIT_VALIDATION_COMMANDS,
    file_extensions = [".gitconfig"],
)
