[bin.agy]
version = "1.2.13"

[bin.agy.github_releases]
repo            = "google-antigravity/antigravity-cli"
bin_name        = "agy"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "agy_cli_{target}.tar.gz"
path_format     = "antigravity"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.agy.github_releases.platforms]
darwin_arm64 = "mac_arm64"
darwin_amd64 = "mac_x64"
linux_amd64  = "linux_x64"
linux_arm64  = "linux_arm64"

[bin.agy.github_releases.checksums]
darwin_arm64 = "092513fcc213cf5034680146a8bad24c4064ecec723a630f42ee7d1046eacc98"
darwin_amd64 = "4375792a19873459b62ff65552a819b68c7d83c47a3a6371e8afcc5d5b7c7b1e"
linux_amd64  = "b0f195d37973be7b08c3b705d7fbbcd948dacb4a3c2176ee52ca29f7159bdc21"
linux_arm64  = "43bf59be5895475f8a32d4f94f1241f665986ea41a3622579e03b74e1b63dcfb"
