[bin.agy]
version = "1.2.16"

[bin.agy.github_releases]
repo            = "google-antigravity/antigravity-cli"
bin_name        = "agy"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "agy_cli_{target}.tar.gz"
path_format     = "antigravity"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.agy.github_releases.platforms]
darwin_arm64 = "mac_arm64"
darwin_amd64 = "mac_x64"
linux_amd64  = "linux_x64"
linux_arm64  = "linux_arm64"

[bin.agy.github_releases.checksums]
darwin_arm64 = "97b03ea3e90916e0c8a49edea615406f8ec69047dde17228a478c1854445d32a"
darwin_amd64 = "c1960f7ae5b4d741af21c17b39cbb280d7bd5973e3deca9aed41ad7cc16c5fa3"
linux_amd64  = "d4247430e04cebdbe1ca93d9ccb483cd2f3daeb4cdb0ace5a71cd130e0bdab84"
linux_arm64  = "a6d269d2764e5636ab2bcda73b78c587fe9d00ead767aa3974574229585ee0d3"
