[bin.agy]
version = "1.3.3"

[bin.agy.github_releases]
repo            = "google-antigravity/antigravity-cli"
bin_name        = "agy"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "agy_cli_{target}.tar.gz"
path_format     = "antigravity"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.agy.github_releases.platforms]
darwin_arm64 = "mac_arm64"
darwin_amd64 = "mac_x64"
linux_amd64  = "linux_x64"
linux_arm64  = "linux_arm64"

[bin.agy.github_releases.checksums]
darwin_arm64 = "c39926f3312e87eaa56d750658cf442669d0a716f49319d06369be7fa80520eb"
darwin_amd64 = "78547d90bfd1559a87ba63e941f9332a0d1889d2de415da337dedec8dc9aa239"
linux_amd64  = "8ee3ca32574c431285efbf4d4732f7f8d53e959370bc4a61646e4fa496f7f2b6"
linux_arm64  = "a9d23fe1d7e5c8471881ab37723571a8d3f24e6ecace8fe082f8c0c8d90f41ca"
