[bin.betterleaks]
version = "1.7.3"

[bin.betterleaks.github_releases]
repo            = "betterleaks/betterleaks"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "v{version}"
filename_format = "betterleaks_{version}_{target}.tar.gz"
path_format     = "betterleaks"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.betterleaks.github_releases.platforms]
darwin_arm64 = "darwin_arm64"
darwin_amd64 = "darwin_x64"
linux_amd64  = "linux_x64"
linux_arm64  = "linux_arm64"

[bin.betterleaks.github_releases.checksums]
darwin_arm64 = "068449bf665a07d17389a38ddee749be7d5484254e9262018e138e94b43f10c0"
darwin_amd64 = "2216363235feb5ad3696f6745c40a78156adce0c05dfb06a5eeca6d25e4aeed2"
linux_amd64  = "9d2ed6fc387bc1c3f95557d5539077b1ce422f0db5ec38db5f14a141ad2947bf"
linux_arm64  = "0541cd2980964a6fb8ea768e8b9507c91a3c06229193462f33a3ecd9cb146b99"
