[bin.chafa]
version = "1.18.2"

# chafa publishes static binaries on hpjansson.org, not GitHub
[bin.chafa.direct_release]
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
filename_format = "chafa-{version}-1-{target}.tar.gz"
path_format     = "chafa-{version}-1-{target}/chafa"
url_format      = "https://hpjansson.org/chafa/releases/static/{filename}"

[bin.chafa.direct_release.platforms]
linux_amd64 = "x86_64-linux-gnu"
linux_arm   = "armv7l-linux-gnu"

[bin.chafa.direct_release.checksums]
linux_amd64 = "deb149bc8823589f635f24db3ecc83b7daa86e4c20d8a9f58e9ce53bd97bdda9"
linux_arm   = "d0ce237308a5b22abed0dd5e5af150cafeb9c90908810e40608389cbad34bfc1"

[bin.chafa.homebrew]
name = "chafa"

[bin.chafa.apt]
name = "chafa"
