[bin.codex]
version = "0.161.0"

[bin.codex.github_releases]
repo            = "openai/codex"
bin_name        = "codex"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "rust-v{version}"
filename_format = "codex-{target}.tar.gz"
path_format     = "codex-{target}"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.codex.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
darwin_amd64 = "x86_64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-musl"
linux_arm64  = "aarch64-unknown-linux-musl"

[bin.codex.github_releases.checksums]
darwin_arm64 = "bd83479f3ae21474c407ec2164fbc2a63fa763f7afbbd123fb6a69c5201cfd38"
darwin_amd64 = "cb3d72225b15f070eabf1b0e3602014ca8bf067e20f11e3b73c88db7b2463853"
linux_amd64  = "b1efb95097660d7f2e5a3887618a23f2ea1b0d548078bf92b0f7a5d229a0cef2"
linux_arm64  = "5c90bf4be3c97fc62fcafb28ec2335ee318e6ecb332e1e8ee3d2c63814a5a26a"
