[bin.delta]
version = "0.19.2"

[bin.delta.github_releases]
repo            = "dandavison/delta"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "delta-{version}-{target}.tar.gz"
path_format     = "delta-{version}-{target}/delta"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

# upstream dropped Intel macOS (x86_64-apple-darwin) builds starting 0.19.0
# https://github.com/dandavison/delta/pull/2074
[bin.delta.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-gnu"
linux_arm64  = "aarch64-unknown-linux-gnu"

[bin.delta.github_releases.checksums]
darwin_arm64 = "9be36612a5a13e9e386dc498fb8e50dc87c72ee42b63db0ea05b32f99a72a69a"
linux_amd64  = "8e695c5f586a8c53d6c3b01be0b4a422ed218bfed2a56191caebe373a1c18ab2"
linux_arm64  = "0bfce159a5cddd5feb3d6db4a616d883ff51253ce08ac7ec11cb1d208cfaab9e"
