[bin.delta]
version = "0.18.2"

[bin.delta.github_releases]
repo            = "dandavison/delta"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "delta-{version}-{target}.tar.gz"
path_format     = "delta-{version}-{target}/delta"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.delta.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
darwin_amd64 = "x86_64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-gnu"
linux_arm64  = "aarch64-unknown-linux-gnu"

[bin.delta.github_releases.checksums]
darwin_arm64 = "6ba38dce9f91ee1b9a24aa4aede1db7195258fe176c3f8276ae2d4457d8170a0"
darwin_amd64 = "e9b5c4a9e73d2119c687e074f0d97f188e30e5fe8ae0e6d455755f74bb5cc0cf"
linux_amd64  = "99607c43238e11a77fe90a914d8c2d64961aff84b60b8186c1b5691b39955b0f"
linux_arm64  = "adf7674086daa4582f598f74ce9caa6b70c1ba8f4a57d2911499b37826b014f9"
