[bin.gh]
version = "2.93.0"

# gh uses OS-capitalized platform strings (macOS vs linux) and zip on darwin
[bin.gh.github_releases]
repo            = "cli/cli"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "v{version}"
filename_format = "gh_{version}_{target}.{ext}"
path_format     = "gh_{version}_{target}/bin/gh"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.gh.github_releases.platforms]
darwin_arm64 = "macOS_arm64"
darwin_amd64 = "macOS_amd64"
linux_amd64  = "linux_amd64"
linux_arm64  = "linux_arm64"

[bin.gh.github_releases.ext]
darwin_arm64 = "zip"
darwin_amd64 = "zip"
linux_amd64  = "tar.gz"
linux_arm64  = "tar.gz"

[bin.gh.github_releases.checksums]
darwin_arm64 = "a86be4e0a86c26456cf71177d6572d6f1165cf1679e532b72f7f15918ee51fd2"
darwin_amd64 = "009425b9d175c482037fe25181817fd6b1ea3ae1f51cfae0e18f29f33d3152ac"
linux_amd64  = "02d1290eba130e0b896f3709ffff22e1c75a51475ddb70476a85abc6b5807af0"
linux_arm64  = "c55feb33684abba57e9909737340d5b39282257c0363e1edde6785ac4a413be7"

[bin.gh.homebrew]
name = "gh"

# apt requires adding the GitHub CLI apt repository first
[bin.gh.apt]
name = "gh"
