[bin.jq]
version = "1.8.2"

[bin.jq.github_releases]
repo            = "jqlang/jq"
external_type   = "file"
executable      = true
checksum_type   = "sha256"
tag_format      = "jq-{version}"
filename_format = "jq-{target}"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.jq.github_releases.platforms]
darwin_arm64 = "macos-arm64"
darwin_amd64 = "macos-amd64"
linux_amd64  = "linux-amd64"
linux_arm64  = "linux-arm64"

[bin.jq.github_releases.checksums]
darwin_arm64 = "2d75340ba57a4b4b4c8708a21c2dc8e958a48aaa8bba13b27f77f6e4c0eca07e"
darwin_amd64 = "e94b266e3c26690550006abe63152b782280f4e14374accdf04cbde844f00bc0"
linux_amd64  = "b1c22172dd303f3be49e935aa56aa48a8b7a46e0bc838b4997d3bb451495870f"
linux_arm64  = "8b85c817833814ddca00a144c33705546355afccf0cf39b188f3cdb48b852309"

[bin.jq.homebrew]
name = "jq"

[bin.jq.apt]
name = "jq"
