[bin.nvim]
version = "0.12.4"

[bin.nvim.github_releases]
repo             = "neovim/neovim"
external_type    = "archive"
checksum_type    = "sha256"
tag_format       = "v{version}"
filename_format  = "nvim-{target}.tar.gz"
path_format      = "nvim"
url_format       = "{base}/{repo}/releases/download/{tag}/{filename}"
strip_components = 1

[bin.nvim.github_releases.platforms]
darwin_arm64 = "macos-arm64"
darwin_amd64 = "macos-x86_64"
linux_amd64  = "linux-x86_64"
linux_arm64  = "linux-arm64"

[bin.nvim.github_releases.checksums]
darwin_arm64 = "51ab83afa66d663627c2ab1be43209b0f4e81360d4598b53efaa4d8195f24c89"
darwin_amd64 = "03fe16f8dd9f1e9eaf52d5e294913a39917b9e2faea30d7fb0fb385fbd36fe59"
linux_amd64  = "012bf3fcac5ade43914df3f174668bf64d05e049a4f032a388c027b1ebd78628"
linux_arm64  = "ceb7e88c6b681f0515d135dcdfad54f5eb4373b25ce6172197cd9a69c758063f"

[bin.nvim.homebrew]
name = "neovim"
cask = false
