[bin.opencode]
version = "1.15.13"

[bin.opencode.github_releases]
repo            = "anomalyco/opencode"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "v{version}"
filename_format = "opencode-{target}.{ext}"
path_format     = "opencode"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.opencode.github_releases.platforms]
linux_amd64 = "linux-x64"
linux_arm64 = "linux-arm64"

[bin.opencode.github_releases.ext]
linux_amd64 = "tar.gz"
linux_arm64 = "tar.gz"

[bin.opencode.github_releases.checksums]
linux_amd64 = "51785a07c009f27c5125a5235c5a0ff78433dace07f73fbc44eb672ead4b3d79"
linux_arm64 = "7a0e5da2427c7804314fe0f87b74b4408467f94e3b8b1a61ba25a1d71fe0b4d2"
