[bin.pi]
version = "0.83.0"

[bin.pi.github_releases]
repo            = "earendil-works/pi"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "v{version}"
filename_format = "pi-{target}.tar.gz"
path_format     = "pi/pi"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.pi.github_releases.platforms]
darwin_arm64 = "darwin-arm64"
darwin_amd64 = "darwin-x64"
linux_amd64  = "linux-x64"
linux_arm64  = "linux-arm64"

[bin.pi.github_releases.checksums]
darwin_arm64 = "147fc3c451ec543a15102af251ce316079c8fcadfe8ae4d3ffee202346e9bed9"
darwin_amd64 = "9ab12e406e545be131d1279a9a2c0d5c0d4a3c6e9d86a52700a7a135a445041b"
linux_amd64  = "b0625eb623197b0afe20c870d21ef2f34481f1504e5777df3f698a66c7636f5f"
linux_arm64  = "b84f9016610c738dd9440df62f649880dbe9951db97a7ae936cbf292850e9802"
