[bin.ripgrep]
version = "15.2.0"

[bin.ripgrep.github_releases]
repo            = "BurntSushi/ripgrep"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "ripgrep-{version}-{target}.tar.gz"
path_format     = "ripgrep-{version}-{target}/rg"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

# ripgrep does not use a v-prefix on its tags
[bin.ripgrep.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
darwin_amd64 = "x86_64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-musl"
linux_arm64  = "aarch64-unknown-linux-gnu"

[bin.ripgrep.github_releases.checksums]
darwin_arm64 = "3750b2e93f37e0c692657da574d7019a101c0084da05a790c83fd335bad973e4"
darwin_amd64 = "af7825fcc69a2afc7a7aea55fc9af90e26421d8f20fe59df32e233c0b8a231c1"
linux_amd64  = "33e15bcf1624b25cdd2a55813a47a2f95dbe126268203e76aa6a585d1e7b149c"
linux_arm64  = "a740b91c82eaf9914cfedd353572f2791cbe0162c84101ee0951058f4dcbc90d"

[bin.ripgrep.homebrew]
name = "ripgrep"

[bin.ripgrep.apt]
name = "ripgrep"
