[bin.sbx]
version = "0.39.0"

[bin.sbx.github_releases]
repo             = "docker/sbx-releases"
external_type    = "archive"
checksum_type    = "sha256"
tag_format       = "v{version}"
filename_format  = "DockerSandboxes-{target}.{ext}"
path_format      = "lib/docker-sbx"
url_format       = "{base}/{repo}/releases/download/{tag}/{filename}"
strip_components = 1

[bin.sbx.github_releases.platforms]
linux_amd64 = "linux-amd64"
linux_arm64 = "linux-arm64"

[bin.sbx.github_releases.ext]
linux_amd64 = "tar.gz"
linux_arm64 = "tar.gz"

[bin.sbx.github_releases.checksums]
linux_amd64 = "2ec45bc7938c20c2f406fe8cc72294ad5a954bdc047601484b89bf1a108311d4"
linux_arm64 = "39c470a5f5e0991b1c2358952e2ab32a7b0309bfa57ac62b6bbc64b466d02c17"
