[bin.sbx]
version = "0.46.0"

[bin.sbx.github_releases]
repo             = "docker/sbx-releases"
external_type    = "archive"
checksum_type    = "sha256"
tag_format       = "v{version}"
filename_format  = "DockerSandboxes-{target}.{ext}"
path_format      = "lib/docker-sbx"
url_format       = "{base}/{repo}/releases/download/{tag}/{filename}"
strip_components = 1

[bin.sbx.github_releases.platforms]
linux_amd64 = "linux-amd64"
linux_arm64 = "linux-arm64"

[bin.sbx.github_releases.ext]
linux_amd64 = "tar.gz"
linux_arm64 = "tar.gz"

[bin.sbx.github_releases.checksums]
linux_amd64 = "edd86e2f21559e190723fd884c3a1dced161a555afdff85c5921ed45e7d6d56e"
linux_arm64 = "b20da2e5e2ba7a67151a19821960c657c08d8fa8dcfdf5e9751f284d6e55ffa8"
