[shellcheck]
version             = "0.11.0"
installation_method = "chezmoi_external"
repo                = "koalaman/shellcheck"
external_type       = "archive-file"
executable          = true
checksum_type       = "sha256"
tag_format          = "v{version}"
filename_format     = "shellcheck-v{version}.{target}.tar.gz"
path_format         = "shellcheck-v{version}/shellcheck"
url_format          = "{base}/{repo}/releases/download/{tag}/{filename}"

[shellcheck.platforms]
darwin_arm64 = "darwin.aarch64"
darwin_amd64 = "darwin.x86_64"
linux_amd64  = "linux.x86_64"
linux_arm64  = "linux.aarch64"

[shellcheck.checksums]
darwin_arm64 = "339b930feb1ea764467013cc1f72d09cd6b869ebf1013296ba9055ab2ffbd26f"
darwin_amd64 = "c2c15e08df0e8fbc374c335b230a7ee958c313fa5714817a59aa59f1aa594f51"
linux_amd64  = "b7af85e41cc99489dcc21d66c6d5f3685138f06d34651e6d34b42ec6d54fe6f6"
linux_arm64  = "68a8133197a50beb8803f8d42f9908d1af1c5540d4bb05fdfca8c1fa47decefc"
