[bin.starship]
version = "1.26.0"

[bin.starship.github_releases]
repo            = "starship/starship"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "v{version}"
filename_format = "starship-{target}.tar.gz"
path_format     = "starship"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.starship.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
darwin_amd64 = "x86_64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-gnu"
linux_arm64  = "aarch64-unknown-linux-musl"

[bin.starship.github_releases.checksums]
darwin_arm64 = "c40b27b11f580411e068f2fa6c1be7830a387c0bc47a94d1d37f32b054c5361d"
darwin_amd64 = "5548f406a4b6f5695903bdea83f77ce47ec12c8c0e62dabd33122d8f133e4207"
linux_amd64  = "321f0dd7af8340a5f2e6a8fec6538a04f617486f9ec70d878f91c09cd8deef22"
linux_arm64  = "dc30189378d2f2e287384e8a692d3f95ad1df64cf0e8c36aa9201516028aed6b"

[bin.starship.homebrew]
name = "starship"
