[bin.zellij]
# version already includes "v" prefix — tag_format uses {version} directly
version = "v0.45.1"

[bin.zellij.github_releases]
repo            = "zellij-org/zellij"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "{version}"
filename_format = "zellij-{target}.tar.gz"
path_format     = "zellij"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.zellij.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
darwin_amd64 = "x86_64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-musl"
linux_arm64  = "aarch64-unknown-linux-musl"

[bin.zellij.github_releases.checksums]
darwin_arm64 = "c029ba4fe1927b79ad9f0cdd59155c4dff80777863c85857d4d09b88b56f9891"
darwin_amd64 = "8e8bea22737d1652278c51fc5c26c7c22c9855d0ebb9634a84b8873823093114"
linux_amd64  = "40bcc2e03f5d5ae8e054e39f676081fe12ab70871506996ba595834c3718eefc"
linux_arm64  = "05f0802afadd53f8db9514e7cae53c9ae8432fed1b35b8294aa816ee3044a16b"

[bin.zellij.homebrew]
name = "zellij"
