[bin.zoxide]
version = "0.10.0"

[bin.zoxide.github_releases]
repo            = "ajeetdsouza/zoxide"
external_type   = "archive-file"
executable      = true
checksum_type   = "sha256"
tag_format      = "v{version}"
filename_format = "zoxide-{version}-{target}.tar.gz"
path_format     = "zoxide"
url_format      = "{base}/{repo}/releases/download/{tag}/{filename}"

[bin.zoxide.github_releases.platforms]
darwin_arm64 = "aarch64-apple-darwin"
darwin_amd64 = "x86_64-apple-darwin"
linux_amd64  = "x86_64-unknown-linux-musl"
linux_arm64  = "aarch64-unknown-linux-musl"

[bin.zoxide.github_releases.checksums]
darwin_arm64 = "b55ae6f2f5f23d0a6ccb3bd4eeb2af9c7e0a6556e5255c82100e40305129bbb0"
darwin_amd64 = "18ab7ae2633ad6e2ab79a4e665cbba1e95b7c872d44523326efb793202451dad"
linux_amd64  = "2d93385b99f3e82cf2701609a1bffcad863fbeb75aa3fe7eb6be4d29be68b1ae"
linux_arm64  = "f1f16c5d6298d63dee467eedea1cdcd8490e43e493bea43acd416dc9033ef641"

[bin.zoxide.homebrew]
name = "zoxide"

[bin.zoxide.apt]
name = "zoxide"
