-- Hammerspoon configuration
-- Generated by Bazel

-- Load modules
local modulePath = hs.configdir .. "/modules/"
local moduleFiles = hs.fs.dir(modulePath)

if moduleFiles then
    for file in moduleFiles do
        if file:sub(-4) == ".lua" then
            local moduleName = file:sub(1, -5)
            require("modules." .. moduleName)
        end
    end
end

-- Load configuration
hs.loadSpoon("SpoonInstaller")
spoon.SpoonInstaller:updateRepo('default')

-- Reload config when any lua file in the config directory changes
function reloadConfig(files)
    local doReload = false
    for _, file in pairs(files) do
        if file:sub(-4) == ".lua" then
            doReload = true
        end
    end
    if doReload then
        hs.reload()
    end
end

hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", reloadConfig):start()
hs.alert.show("Hammerspoon config loaded")