"""
Implementation of ZSH configuration rules.
"""

load("//rules/common:rule_utils.bzl", "create_config_rule", "create_config_test_rule")

# Create zsh_config rule using common utilities
zsh_config = create_config_rule(
    rule_name = "zsh",
    file_extension = ".zsh",
    mnemonic = "ZshConfig",
    allowed_extensions = None,  # Allow all file types
    header_template = "# ZSH configuration generated by Bazel",
    footer_template = "# End of generated ZSH configuration",
)

# Define validation commands for zsh
_ZSH_VALIDATION_COMMANDS = [
    # Validate syntax by running zsh -n (no execution, just syntax check)
    '"{tool_path}" -n "{config_path}" || {{ echo "ZSH configuration has syntax errors"; exit 1; }}',
]

# Create zsh_test rule using common utilities
zsh_test = create_config_test_rule(
    rule_name = "zsh",
    toolchain_type = "//toolchains/zsh:toolchain_type",
    validation_commands = _ZSH_VALIDATION_COMMANDS,
    file_extensions = [".zsh"],
)
