#!/bin/bash
# ZSH configuration installer
# Generated by Bazel

set -euo pipefail

INSTALL_DIR="{{INSTALL_DIR}}"
CONFIG_FILES="{{CONFIG_FILES}}"
PLUGINS="{{PLUGINS}}"
THEMES="{{THEMES}}"
OPTIONS="{{OPTIONS}}"
ALIASES="{{ALIASES}}"
ENV_VARS="{{ENV_VARS}}"
COMPLETION_SETTINGS="{{COMPLETION_SETTINGS}}"

# Create ~/.zsh directory if it doesn't exist
mkdir -p "${INSTALL_DIR}/.zsh"

echo "Installing ZSH configuration files..."

# Install configuration files
for file in ${CONFIG_FILES}; do
  filename=$(basename "$file")
  cp "$file" "${INSTALL_DIR}/$filename"
  echo "Installed ${filename}"
done

# Create local customization files if they don't exist
touch "${INSTALL_DIR}/.zshrc.local"
touch "${INSTALL_DIR}/.zshenv.local"

echo "ZSH configuration installed successfully!"
echo "You may need to restart your shell for changes to take effect."