# ~/.zshrc
# Generated by Bazel - do not edit directly

# Load local environment variables if present
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local

# Options
setopt autocd extendedglob nomatch
unsetopt beep
setopt notify
setopt hist_verify hist_ignore_dups hist_ignore_space

# History settings
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Basic completion settings
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt completealiases

# Aliases
alias ls='ls --color=auto'
alias ll='ls -la'
alias grep='grep --color=auto'
alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gs='git status'

# Plugin loading logic
# This is a placeholder - in a real implementation, you would load plugins
# based on the configuration

# Theme loading logic
# This is a placeholder - in a real implementation, you would load themes
# based on the configuration

# Load local customizations if present
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local