def _tmux_gz_download_impl(repository_ctx):
    repository_ctx.download(
        url = repository_ctx.attr.urls,
        sha256 = repository_ctx.attr.sha256,
        output = "tmux.gz",
    )

    # Decompress it
    repository_ctx.execute(["gzip", "-d", "tmux.gz"])

    # Make it executable
    repository_ctx.execute(["chmod", "+x", "tmux"])

    repository_ctx.file(
        "BUILD.bazel",
        """
exports_files(["tmux"])
        """,
    )

tmux_gz_download = repository_rule(
    implementation = _tmux_gz_download_impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
    },
)

def _tmux_hub_impl(repository_ctx):
    # This repository rule generates the central @tmux repository with a BUILD.bazel
    # that uses select() to point to the correct platform-specific binary.

    content = """# Generated by tmux module extension
package(default_visibility = ["//visibility:public"])

alias(
    name = "bin",
    actual = select({
        "@platforms//os:linux": ":linux_bin",
        "@platforms//os:macos": ":macos_bin",
        "//conditions:default": "@platforms//:incompatible",
    }),
)

alias(
    name = "linux_bin",
    actual = select({
        "@platforms//cpu:x86_64": "@tmux_linux_amd64//:tmux",
        "@platforms//cpu:aarch64": "@tmux_linux_arm64//:tmux",
        "//conditions:default": "@platforms//:incompatible",
    }),
)

alias(
    name = "macos_bin",
    actual = select({
        "@platforms//cpu:x86_64": "@tmux_darwin_amd64//:tmux",
        "@platforms//cpu:aarch64": "@tmux_darwin_arm64//:tmux",
        "//conditions:default": "@platforms//:incompatible",
    }),
)
"""
    repository_ctx.file("BUILD.bazel", content)

tmux_hub = repository_rule(
    implementation = _tmux_hub_impl,
    attrs = {
        "platforms_info": attr.string_dict(),
    },
    doc = "Creates the central hub repository for the tmux binary.",
)
