load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def _tmux_hub_impl(repository_ctx):
    # This repository rule generates the central @tmux repository with a BUILD.bazel
    # that uses select() to point to the correct platform-specific binary.

    build_file_content = """# Generated by tmux module extension
package(default_visibility = ["//visibility:public"])

alias(
    name = "bin",
    actual = select({
        "@platforms//os:linux": ":linux_bin",
        "@platforms//os:macos": ":macos_bin",
        "//conditions:default": "@platforms//:incompatible",
    }),
)

alias(
    name = "linux_bin",
    actual = select({
        "@platforms//cpu:x86_64": "@tmux_linux_amd64//:tmux",
        "@platforms//cpu:aarch64": "@tmux_linux_arm64//:tmux",
        "//conditions:default": "@platforms//:incompatible",
    }),
)

alias(
    name = "macos_bin",
    actual = select({
        "@platforms//cpu:x86_64": "@tmux_darwin_amd64//:tmux",
        "@platforms//cpu:aarch64": "@tmux_darwin_arm64//:tmux",
        "//conditions:default": "@platforms//:incompatible",
    }),
)
"""

    # Substitute the repo prefix (which is the name of this hub repo, usually "tmux")
    build_file_content = build_file_content.replace("{repo_prefix}", repository_ctx.attr.name)

    repository_ctx.file("BUILD.bazel", build_file_content)

tmux_hub = repository_rule(
    implementation = _tmux_hub_impl,
    doc = "Creates the central hub repository for the tmux binary.",
)
