[ai.skills.external.superpowers]
repo = "obra/superpowers"
ref = "d884ae04edebef577e82ff7c4e143debd0bbec99" # 2026-07-02
sha256 = "d2c15e07a4637bffc7df15daa062eeb569c9adf6d6ad6ec08dec4ce6539b3910"

[ai.skills.external.superpowers.skills]
brainstorming = "present"
dispatching-parallel-agents = "present"
executing-plans = "present"
finishing-a-development-branch = "present"
receiving-code-review = "present"
requesting-code-review = "present"
subagent-driven-development = "present"
systematic-debugging = "present"
test-driven-development = "present"
using-git-worktrees = "present"
using-superpowers = "present"
verification-before-completion = "present"
writing-plans = "present"
writing-skills = "present"
