# Font configuration
# Supported fonts:
# - fira_mono: Fira Mono Nerd Font
# - jetbrains_mono: JetBrains Mono Nerd Font

[fonts.fira_mono]
name = "FiraMono"
version = "v3.4.0"
sha256 = "2e4adc97fefdfa2ad70a6e6e79bc0418acd401a305bcb5fcd848a84e03e35a74"
installation = "external-sources"

[fonts.jetbrains_mono]
name = "JetBrainsMono"
version = "v3.4.0"
sha256 = "ef552a3e638f25125c6ad4c51176a6adcdce295ab1d2ffacf0db060caf8c1582"
installation = "external-sources"
