[mise]
version = "v2026.3.10"
installation = "external-sources"

[mise.checksums]
darwin_arm64 = "c7a0eb1035de974b42d36b69c4b55b836c06b455b990dd6ac530aaf05d4a8a17"
darwin_amd64 = "a945255eb432b900d9db1eaccba14e5ef99c719a5d0ad1a983abc00b2f17388f"
linux_amd64 = "5fbb922019f56cfd33fc8bccedb80e0b1a2dd5d8f8567b076c1bbec7ff30548c"
linux_arm64 = "bbbd6e856d9fd53ffaa0773d0625f5a8c2f393610034712a389c68bbc5ad0f84"

[mise.settings]
disable_hints = ["self_update"]

[mise.global_tools]

  [mise.global_tools.node]
  version = "lts"
  installation = "mise"

  [mise.global_tools.python]
  version = "3.14"
  installation = "mise"

  [mise.global_tools.pnpm]
  version = "10.33.0"
  installation = "mise"

  [mise.global_tools.java]
  version = "temurin-21.0.10+7"
  installation = "mise"

  [mise.global_tools.rust]
  version = "1.94.0"
  installation = "mise"

  [mise.global_tools.uv]
  version = "0.11.3"
  installation = "mise"

  [mise.global_tools."npm:@google/gemini-cli"]
  version = "0.36.0"
  installation = "mise"

  [mise.global_tools.bun]
  version = "1.3.11"
  installation = "mise"
