[mise]
version = "v2026.3.5"
installation = "external-sources"

[mise.checksums]
darwin_arm64 = "273595c272b5111f5791452ac4cc4f404e991e3b9e257e15cffd820c78212f21"
darwin_amd64 = "9682e739abe95a55ea2829103e3b70e023c7a4c931639cc003b25b8c05744b87"
linux_amd64 = "18c0934d8ffcb84712b4cf52becfd67f6b1241fab110ad6dde34f51dfb206f8f"
linux_arm64 = "070eb5a993280d6c67a96ba061bc0244385ca9e79c0c7db10c1865f14a474d6e"

[mise.settings]
disable_hints = ["self_update"]

[mise.global_tools]

  [mise.global_tools.node]
  version = "lts"
  enabled = true

  [mise.global_tools.python]
  version = "3.14"
  enabled = true

  [mise.global_tools.pnpm]
  version = "10.31.0"
  enabled = true

  [mise.global_tools.java]
  version = "temurin-21.0.10+7"
  enabled = true

  [mise.global_tools.rust]
  version = "1.94.0"
  enabled = true

  [mise.global_tools.uv]
  version = "0.10.9"
  enabled = true

  [mise.global_tools."npm:@google/gemini-cli"]
  version = "0.32.1"
  enabled = true

  [mise.global_tools.bun]
  version = "1.3.10"
  enabled = true
