[mise]
version = "v2026.4.17"
installation = "external-sources"

[mise.checksums]
darwin_arm64 = "ac0251f8ccbd48de250aa866a05637b74439b22f815a894bd47fce5d52e209e7"
darwin_amd64 = "7925831a68bb119ae0a744408ab646b476f6309720b46d7f5ab466613ca7ada8"
linux_amd64 = "e5b07552c8b7799aebe39a8015898b9bb9a436fb6bb1595db507887ec253cb0e"
linux_arm64 = "4cdeb9fa79e0ad8bfdf4d0aa42f17f26d6602b033df586ed08e4435602ffadb1"

[mise.settings]
# Configuration settings: https://mise.jdx.dev/configuration/settings.html
cache_prune_age = "60 days"
disable_hints = ["self_update"]
http_retries = 5
install_before = "7d"
[mise.settings.npm]
package_manager = "bun"

[mise.global_tools]

  [mise.global_tools.python]
  version = "3.14"
  installation = "mise"

  [mise.global_tools.pnpm]
  version = "10.33.0"
  installation = "mise"

  [mise.global_tools.java]
  version = "temurin-21"
  installation = "mise"

  [mise.global_tools.rust]
  version = "1.95.0"
  installation = "mise"

  [mise.global_tools.uv]
  version = "0.11.7"
  installation = "mise"

  [mise.global_tools.bun]
  version = "1.3.12"
  installation = "mise"

  [mise.global_tools.node]
  version = "22"
  installation = "mise"

  [mise.global_tools.gemini-cli]
  version = "0.38.2"
  installation = "mise"
