# chezmoi data file - defines template variables available in templates
# See: https://www.chezmoi.io/reference/special-files/chezmoidata-format/

# Git personal configuration - all-or-nothing feature flag
[git.personal]
enabled = true
name = "Mike Kobit"
email = "mkobit@gmail.com"
signing_key = "1698254E135D7ADE"
gpg_sign = true

[bazelisk]
version = "1.27.0"
installation = "external-sources"

[bazelisk.checksums] # publishes shas
darwin_arm64 = "8bf08c894ccc19ef37f286e58184c3942c58cb08da955e990522703526ddb720"
darwin_amd64 = "d8b00ea975c823e15263c80200ac42979e17368547fbff4ab177af035badfa83"
linux_amd64 = "e1508323f347ad1465a887bc5d2bfb91cffc232d11e8e997b623227c6b32fb76"

[fzf]
version = "0.65.2"
installation = "external-sources"

[fzf.checksums] # publishes shas
darwin_arm64 = "a1464f1d4b75c3a92975f67055f9e407800ed35820ea7d73f2afb90aeb0491e8"
darwin_amd64 = "3bb8b0e746b6238aa2ce43550c06f16a81fc9a46687b06456d996cb54be762e4"
linux_amd64 = "5eb8efc0e94aa559f84ea83eeba99bea7dce818e63f92b4b62e60663220f1c14"

[ripgrep]
version = "14.1.1"
installation = "external-sources"

[ripgrep.checksums] # publishes shas as seperate files
darwin_arm64 = "24ad76777745fbff131c8fbc466742b011f925bfa4fffa2ded6def23b5b937be"
darwin_amd64 = ""
linux_amd64 = ""

[fd]
version = "10.3.0"
installation = "external-sources"

[fd.checksums]
darwin_arm64 = "0570263812089120bc2a5d84f9e65cd0c25e4a4d724c80075c357239c74ae904"  # fd-v10.3.0-aarch64-apple-darwin.tar.gz
darwin_amd64 = "50d30f13fe3d5914b14c4fff5abcbd4d0cdab4b855970a6956f4f006c17117a3"  # fd-v10.3.0-x86_64-apple-darwin.tar.gz
linux_amd64 = "2b6bfaae8c48f12050813c2ffe1884c61ea26e750d803df9c9114550a314cd14"  # fd-v10.3.0-x86_64-unknown-linux-musl.tar.gz

[bat]
version = "0.25.0"
installation = "external-sources"

[bat.checksums] # bat doesn't publish SHA files right now
darwin_arm64 = ""
darwin_amd64 = ""
linux_amd64 = ""

[zoxide]
version = "0.9.8"
installation = "external-sources"

[zoxide.checksums] # zoxide doesn't publish SHA files right now
darwin_arm64 = ""
darwin_amd64 = ""
linux_amd64 = ""

[zsh.oh-my-zsh]
installation = "external-sources"
sha = "9e23925b8581d22033f07f1983587412d3761494"
plugins = ["git", "colored-man-pages"]

[zsh.oh-my-zsh.powerlevel10k]
enabled = false
version = "v1.20.0"
