# chezmoi data file - defines template variables available in templates
# See: https://www.chezmoi.io/reference/special-files/chezmoidata-format/

# Git personal configuration - all-or-nothing feature flag
[git.personal]
enabled = true
name = "Mike Kobit"
email = "mkobit@gmail.com"
signing_key = "1698254E135D7ADE"
gpg_sign = true

[bazelisk]
version = "1.27.0"
installation = "external-sources"

[bazelisk.checksums]
darwin_arm64 = "173c5b367b485a30ce58c1d0d560b39d257a2d7a3c859c45d7d05eb61605a2a1"
darwin_amd64 = ""
linux_amd64 = ""

[fzf]
version = "0.65.2"
installation = "external-sources"

[fzf.checksums]
darwin_arm64 = "a1464f1d4b75c3a92975f67055f9e407800ed35820ea7d73f2afb90aeb0491e8"
darwin_amd64 = ""
linux_amd64 = ""

[ripgrep]
version = "14.1.1"
installation = "external-sources"

[ripgrep.checksums]
darwin_arm64 = "24ad76777745fbff131c8fbc466742b011f925bfa4fffa2ded6def23b5b937be"
darwin_amd64 = ""
linux_amd64 = ""

[fd]
version = "10.3.0"
installation = "external-sources"

[fd.checksums]
darwin_arm64 = ""
darwin_amd64 = ""
linux_amd64 = ""

[bat]
version = "0.25.0"
installation = "external-sources"

[bat.checksums]
darwin_arm64 = "b3ed5a7515545445881f1036f0cc1b708c2b86cbce01c1b4033f38e0cfcc7b3c"
darwin_amd64 = ""
linux_amd64 = ""

[zoxide]
version = "0.9.8"
installation = "external-sources"

[zoxide.checksums]
darwin_arm64 = "3d1ec4af7f3d351629f500b432e6c735caf3216ab3eaa76dbe8ffbc8f3006f5a"
darwin_amd64 = ""
linux_amd64 = ""

[zsh.oh-my-zsh]
installation = "external-sources"
sha = "9e23925b8581d22033f07f1983587412d3761494"
plugins = ["git", "colored-man-pages"]

[zsh.oh-my-zsh.powerlevel10k]
enabled = false
version = "v1.20.0"
