import argparse
import tomllib
import os
from pathlib import Path
from typing import Any


def generate_claude(manifest: dict[str, Any], output_root: Path) -> None:
    """Generates Claude configuration files."""
    claude_root = output_root / "dot_claude"

    # Skills
    skills_dir = claude_root / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    for skill in manifest.get("skill", []):
        skill_name = skill["name"]
        skill_path = skills_dir / skill_name
        skill_path.mkdir(exist_ok=True)

        content = "<!--\n"
        content += (
            "  WARNING: This file is auto-generated from src/agents/manifest.toml.\n"
        )
        content += "  Do not edit this file directly.\n"
        content += "-->\n"
        content += "---\n"
        content += f"name: {skill_name}\n"
        content += f"description: {skill.get('description', '')}\n"
        if "allowed_tools" in skill:
            content += f"allowed-tools: {skill['allowed_tools']}\n"
        content += "---\n\n"
        content += skill["content"]

        with open(skill_path / "SKILL.md", "w") as f:
            f.write(content)

    # Commands
    commands_dir = claude_root / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    for command in manifest.get("command", []):
        cmd_name = command["name"]
        # Convert colon notation to directory structure
        # e.g. claude:new:command -> claude/new/command.md
        parts = cmd_name.split(":")
        cmd_path = commands_dir.joinpath(*parts).with_suffix(".md")
        cmd_path.parent.mkdir(parents=True, exist_ok=True)

        content = "<!--\n"
        content += (
            "  WARNING: This file is auto-generated from src/agents/manifest.toml.\n"
        )
        content += "  Do not edit this file directly.\n"
        content += "-->\n"
        content += "---\n"
        content += f"description: {command.get('description', '')}\n"
        if "argument_hint" in command:
            content += f"argument-hint: {command['argument_hint']}\n"
        if "allowed_tools" in command:
            content += f"allowed-tools: {command['allowed_tools']}\n"
        content += "---\n\n"
        content += command["content"]

        with open(cmd_path, "w") as f:
            f.write(content)


def generate_cursor(manifest: dict[str, Any], output_root: Path) -> None:
    """Generates Cursor configuration (.cursorrules)."""
    # Assuming dot_cursorrules is the target for home directory installation via chezmoi
    # or dot_cursor/rules for project specific.
    # The user asked for "Enable in home dir", so we'll put it in dot_cursorrules
    # which usually implies ~/.cursorrules if chezmoi maps it there.
    # Wait, chezmoi usually ignores dot_ files starting with dot_.
    # 'dot_cursorrules' -> '.cursorrules'

    cursor_rules_path = output_root / "dot_cursorrules"

    content = ""

    content += "# WARNING: This file is auto-generated from src/agents/manifest.toml.\n"
    content += "# Do not edit this file directly.\n\n"

    # System Prompt
    if "system" in manifest and "prompt" in manifest["system"]:
        content += manifest["system"]["prompt"] + "\n\n"

    content += "# Available Tools & Commands\n\n"

    for command in manifest.get("command", []):
        content += f"## {command['name']}\n"
        content += f"{command.get('description', '')}\n"
        if "argument_hint" in command:
            content += f"Usage: {command['name']} {command['argument_hint']}\n"
        content += "\n"

    for skill in manifest.get("skill", []):
        content += f"## Skill: {skill['name']}\n"
        content += f"{skill.get('description', '')}\n\n"

    with open(cursor_rules_path, "w") as f:
        f.write(content)


def generate_gemini(manifest: dict[str, Any], output_root: Path) -> None:
    """Generates Gemini CLI configuration."""
    # Placeholder for Gemini.
    # We will create a markdown file that can be used as a system instruction.
    # path: dot_config/google-gemini-cli/instructions.md (Guessing path)

    gemini_dir = output_root / "dot_config" / "google-gemini-cli"
    gemini_dir.mkdir(parents=True, exist_ok=True)

    content = "# System Instructions\n"
    content += "<!-- WARNING: This file is auto-generated from src/agents/manifest.toml. Do not edit directly. -->\n\n"
    if "system" in manifest and "prompt" in manifest["system"]:
        content += manifest["system"]["prompt"] + "\n\n"

    content += "# Commands\n\n"
    for command in manifest.get("command", []):
        content += f"## {command['name']}\n"
        content += command["content"] + "\n\n"

    with open(gemini_dir / "instructions.md", "w") as f:
        f.write(content)


def main() -> None:
    if "BUILD_WORKSPACE_DIRECTORY" in os.environ:
        os.chdir(os.environ["BUILD_WORKSPACE_DIRECTORY"])

    parser = argparse.ArgumentParser(
        description="Generate agent configurations from manifest."
    )
    parser.add_argument("--manifest", required=True, help="Path to manifest.toml")
    parser.add_argument(
        "--output", required=True, help="Root of chezmoi source directory (src/chezmoi)"
    )

    args = parser.parse_args()

    with open(args.manifest, "rb") as f:
        manifest = tomllib.load(f)

    output_root = Path(args.output)
    output_root.mkdir(parents=True, exist_ok=True)

    print(f"Generating configuration from {args.manifest} to {output_root}...")

    generate_claude(manifest, output_root)
    generate_cursor(manifest, output_root)
    generate_gemini(manifest, output_root)

    print("Generation complete.")


if __name__ == "__main__":
    main()
