import tomllib
import os
from pathlib import Path
from typing import Any
import click

def load_agents_data(agents_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Loads agent configurations from TOML files in subdirectories."""
    data: dict[str, list[dict[str, Any]]] = {
        "command": [],
        "skill": [],
        "role": []
    }

    # Walk through subdirectories
    for root, _, files in os.walk(agents_dir):
        for file in files:
            if file.endswith(".toml"):
                filepath = Path(root) / file
                try:
                    with open(filepath, "rb") as f:
                        item = tomllib.load(f)

                    # Determine type from file content or directory name if not specified
                    item_type = item.get("type")
                    if not item_type:
                        # Fallback to parent directory name
                        parent_dir = filepath.parent.name
                        # simple singularization
                        if parent_dir.endswith("s"):
                            item_type = parent_dir[:-1]
                        else:
                            item_type = parent_dir

                    if item_type in data:
                        data[item_type].append(item)
                    else:
                        click.echo(f"Warning: Unknown item type '{item_type}' in {filepath}", err=True)

                except Exception as e:
                    click.echo(f"Error loading {filepath}: {e}", err=True)

    return data

def generate_claude(data: dict[str, list[dict[str, Any]]], output_root: Path) -> None:
    """Generates Claude configuration files."""
    claude_root = output_root / "dot_claude"

    # Skills
    skills_dir = claude_root / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    for skill in data.get("skill", []):
        skill_name = skill["name"]
        skill_path = skills_dir / skill_name
        skill_path.mkdir(exist_ok=True)

        content = "---\n"
        content += "# WARNING: This file is auto-generated from src/agents/.\n"
        content += "# Do not edit this file directly.\n"
        content += f"name: {skill_name}\n"
        content += f"description: {skill.get('description', '')}\n"
        if "allowed_tools" in skill:
            content += f"allowed-tools: {skill['allowed_tools']}\n"
        content += "---\n\n"
        content += skill.get("instruction", "")

        with open(skill_path / "SKILL.md", "w") as f:
            f.write(content)

    # Commands
    commands_dir = claude_root / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    for command in data.get("command", []):
        cmd_name = command["name"]
        # Convert colon notation to directory structure
        # e.g. claude:new:command -> claude/new/command.md
        parts = cmd_name.split(":")
        cmd_path = commands_dir.joinpath(*parts).with_suffix(".md")
        cmd_path.parent.mkdir(parents=True, exist_ok=True)

        content = "---\n"
        content += "# WARNING: This file is auto-generated from src/agents/.\n"
        content += "# Do not edit this file directly.\n"
        content += f"description: {command.get('description', '')}\n"
        if "argument_hint" in command:
             content += f"argument-hint: {command['argument_hint']}\n"
        if "allowed_tools" in command:
             content += f"allowed-tools: {command['allowed_tools']}\n"
        content += "---\n\n"
        content += command.get("instruction", "")

        with open(cmd_path, "w") as f:
            f.write(content)

def generate_cursor(data: dict[str, list[dict[str, Any]]], output_root: Path) -> None:
    """Generates Cursor configuration (.cursorrules)."""
    cursor_rules_path = output_root / "dot_cursorrules"

    content = ""
    content += "# WARNING: This file is auto-generated from src/agents/.\n"
    content += "# Do not edit this file directly.\n\n"

    # Roles (System Prompts) - Aggregate all roles
    for role in data.get("role", []):
        content += f"# {role.get('name', 'System')}\n\n"
        content += role.get("instruction", "") + "\n\n"

    content += "# Available Tools & Commands\n\n"

    for command in data.get("command", []):
        content += f"## {command['name']}\n"
        content += f"{command.get('description', '')}\n"
        if "argument_hint" in command:
            content += f"Usage: {command['name']} {command['argument_hint']}\n"
        content += "\n"

    for skill in data.get("skill", []):
        content += f"## Skill: {skill['name']}\n"
        content += f"{skill.get('description', '')}\n\n"

    with open(cursor_rules_path, "w") as f:
        f.write(content)

def generate_gemini(data: dict[str, list[dict[str, Any]]], output_root: Path) -> None:
    """Generates Gemini CLI configuration."""
    gemini_dir = output_root / "dot_config" / "google-gemini-cli"
    gemini_dir.mkdir(parents=True, exist_ok=True)

    content = "# System Instructions\n"
    content += "<!-- WARNING: This file is auto-generated from src/agents/. Do not edit directly. -->\n\n"

    # Roles
    for role in data.get("role", []):
        content += role.get("instruction", "") + "\n\n"

    content += "# Commands\n\n"
    for command in data.get("command", []):
        content += f"## {command['name']}\n"
        content += command.get("instruction", "") + "\n\n"

    with open(gemini_dir / "instructions.md", "w") as f:
        f.write(content)

@click.command()
@click.option(
    "--agents-dir",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="Directory containing agent TOML files (src/agents)",
)
@click.option(
    "--output",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="Root of chezmoi source directory (src/chezmoi)",
)
def main(agents_dir: Path, output: Path) -> None:
    """Generate agent configurations from TOML files."""
    if "BUILD_WORKSPACE_DIRECTORY" in os.environ:
        os.chdir(os.environ["BUILD_WORKSPACE_DIRECTORY"])

    data = load_agents_data(agents_dir)

    output.mkdir(parents=True, exist_ok=True)

    click.echo(f"Generating configuration from {agents_dir} to {output}...")

    generate_claude(data, output)
    generate_cursor(data, output)
    generate_gemini(data, output)

    click.echo("Done.")

if __name__ == "__main__":
    main()
