name: Verify

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          pipx install poetry==1.8.3
          pipx ensurepath
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Dependency check
        run: poetry run deptry .
      - name: Format Check
        run: poetry run ruff format --check
      - name: Lint
        run: poetry run ruff check .
      - name: Type check
        run: poetry run pyright
      - name: Run tests
        run: poetry run pytest --cov=src --cov-report=term-missing
