name: "Build"
on: [push, pull_request]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew build --continue
      - name: Upload Reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: build/reports