name: Validate Agent Configuration

on:
  push:
    paths:
      - '.agents/**'
  pull_request:
    paths:
      - '.agents/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: bazel-contrib/setup-bazel@e8776f58fb6a6e9055cbaf1b38c52ccc5247e9c4 # v0.8.1

      - name: Make snapshot script executable
        run: chmod +x .agents/jules/configuration_snapshot.sh

      - name: Run snapshot script
        run: ./.agents/jules/configuration_snapshot.sh
